djangopractice/djangopractice/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")), #include all the urls from hello app
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

djangopractice/hello/urls.py
from django.urls import path
from . import views #. means the current directory
urlpatterns = [
    path("<str:name>",views.greet,name="greet"),
    path("",views.index, name="index"),
    path("brian",views.brian, name="brian")
    
]

djangopractice/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index,name="index")
]

djangopractice/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks" #the app named is used for non hard coded links
urlpatterns = [
     path("",views.index,name="index"),
     path("add", views.add, name="add")
]

djangopractice/hello/models.py
from django.db import models

# Create your models here.

djangopractice/newyear/models.py
from django.db import models

# Create your models here.

djangopractice/tasks/models.py
from django.db import models

# Create your models here.

djangopractice/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def greet(request, name):
    return render(request, "hello/greet.html",{
        "name": name.capitalize()
    })
    #return HttpResponse(f"Hello, {name.capitalize()}!")

djangopractice/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.date
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

djangopractice/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
#tasks = ["foo","bar","baz"]
# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task") #inputs for the form
    priority = forms.IntegerField(label="Priority", min_value=1,max_value=10)

def index(request):
    if "tasks" not in request.session: #make the 'task' variable session based
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST": #if the user submitted some form data
        form = NewTaskForm(request.POST) #param has all the data the user submitted when the user pressed submit
        if form.is_valid():
            task = form.cleaned_data["task"] #variable containing all the cleaned data defined in the NewTaskForm class
            request.session["tasks"] += [task] #change the tasks variable's data
            return HttpResponseRedirect(reverse("tasks:index")) #reverse means figure out what thee url of the tasks index url is
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
        
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

djangopractice/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

djangopractice/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
    </body>
</html>

djangopractice/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it new year's?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

djangopractice/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Add Tasks</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">Index</a>
{% endblock %}

djangopractice/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No Tasks</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

djangopractice/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
    </head>
    <body>
        {% block body %}
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% endfor %}
        </ul>
        {% endblock %}
    </body>
</html>